project:
  type: website

website:
  title: "Prof. Davy Baia"
  description: "Página com as disciplinas ministradas na UFAL - Campus CECA (Rio Largo)"
  navbar:
    left:
      - href: index.qmd
        text: Início

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
